-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 21:13:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio1 TP4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ejercicio1 TP4` ;

-- -----------------------------------------------------
-- Schema Ejercicio1 TP4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio1 TP4` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio1 TP4` ;

-- -----------------------------------------------------
-- Table `Ejercicio1 TP4`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio1 TP4`.`Alumnos` (
  `Cod_Matricula` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Alumno` VARCHAR(50) NOT NULL,
  `DNI` INT NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Cod_Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio1 TP4`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio1 TP4`.`Curso` (
  `Cod_Curso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Cod_Curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio1 TP4`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio1 TP4`.`Profesor` (
  `ID_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Especialidad` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio1 TP4`.`Alumnos_has_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio1 TP4`.`Alumnos_has_Curso` (
  `Alumnos_Cod_Matricula` INT NOT NULL,
  `Curso_Cod_Curso` INT NOT NULL,
  PRIMARY KEY (`Alumnos_Cod_Matricula`, `Curso_Cod_Curso`),
  CONSTRAINT `fk_Alumnos_has_Curso_Alumnos1`
    FOREIGN KEY (`Alumnos_Cod_Matricula`)
    REFERENCES `Ejercicio1 TP4`.`Alumnos` (`Cod_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Curso_Curso1`
    FOREIGN KEY (`Curso_Cod_Curso`)
    REFERENCES `Ejercicio1 TP4`.`Curso` (`Cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Alumnos_has_Curso_Curso1_idx` ON `Ejercicio1 TP4`.`Alumnos_has_Curso` (`Curso_Cod_Curso` ASC) VISIBLE;

CREATE INDEX `fk_Alumnos_has_Curso_Alumnos1_idx` ON `Ejercicio1 TP4`.`Alumnos_has_Curso` (`Alumnos_Cod_Matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ejercicio1 TP4`.`Curso_has_Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio1 TP4`.`Curso_has_Profesor` (
  `Curso_Cod_Curso` INT NOT NULL,
  `Profesor_ID_Profesor` INT NOT NULL,
  PRIMARY KEY (`Curso_Cod_Curso`, `Profesor_ID_Profesor`),
  CONSTRAINT `fk_Curso_has_Profesor_Curso1`
    FOREIGN KEY (`Curso_Cod_Curso`)
    REFERENCES `Ejercicio1 TP4`.`Curso` (`Cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Profesor_Profesor1`
    FOREIGN KEY (`Profesor_ID_Profesor`)
    REFERENCES `Ejercicio1 TP4`.`Profesor` (`ID_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_has_Profesor_Profesor1_idx` ON `Ejercicio1 TP4`.`Curso_has_Profesor` (`Profesor_ID_Profesor` ASC) VISIBLE;

CREATE INDEX `fk_Curso_has_Profesor_Curso1_idx` ON `Ejercicio1 TP4`.`Curso_has_Profesor` (`Curso_Cod_Curso` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
