-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 21:09:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio3 TP4
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ejercicio2 TP4` ;

-- -----------------------------------------------------
-- Schema Ejercicio3 TP4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio2 TP4` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio2 TP4` ;

-- -----------------------------------------------------
-- Table `Ejercicio3 TP4`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2 TP4`.`Localidad` (
  `ID_Localidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Codigo_Postal` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_Localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio2 TP4`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2 TP4`.`Provincia` (
  `ID_Provincia` INT NOT NULL,
  `Nombre_Provincia` VARCHAR(45) NOT NULL,
  `Localidad_ID_Localidad` INT NOT NULL,
  PRIMARY KEY (`ID_Provincia`),
  CONSTRAINT `fk_Provincia_Localidad1`
    FOREIGN KEY (`Localidad_ID_Localidad`)
    REFERENCES `Ejercicio3 TP4`.`Localidad` (`ID_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Provincia_Localidad1_idx` ON `Ejercicio2 TP4`.`Provincia` (`Localidad_ID_Localidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ejercicio3 TP4`.`País`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2 TP4`.`País` (
  `ID_País` INT NOT NULL,
  `Nombre_pais` VARCHAR(45) NOT NULL,
  `Provincia_ID_Provincia` INT NOT NULL,
  PRIMARY KEY (`ID_País`),
  CONSTRAINT `fk_País_Provincia1`
    FOREIGN KEY (`Provincia_ID_Provincia`)
    REFERENCES `Ejercicio2 TP4`.`Provincia` (`ID_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_País_Provincia1_idx` ON `Ejercicio2 TP4`.`País` (`Provincia_ID_Provincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Ejercicio3 TP4`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio2 TP4`.`Empleado` (
  `ID_Empleado` INT NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Fecha_Alta` VARCHAR(45) NOT NULL,
  `Localidad_ID_Localidad` INT NOT NULL,
  PRIMARY KEY (`ID_Empleado`),
  CONSTRAINT `fk_Empleado_Localidad1`
    FOREIGN KEY (`Localidad_ID_Localidad`)
    REFERENCES `Ejercicio2 TP4`.`Localidad` (`ID_Localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado_Localidad1_idx` ON `Ejercicio2 TP4`.`Empleado` (`Localidad_ID_Localidad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
